const albumCovers = [
  {
    title: 'Maple Syrup',
    subtitle: 'Barca',
    image: 'https://i.postimg.cc/BQ3snspp/maplesyrup.jpg',
    link: 'https://open.spotify.com/album/26VgzLAyBkVIn8SesEB6oB?si=Q-TsDWcCRJGWjbYRCT4kuQ',
  },
  {
    title: 'yeyts',
    subtitle: 'seat back',
    image: 'https://i.postimg.cc/fL0ZJR12/yeyts.jpg',
    link: 'https://open.spotify.com/album/7xc1FPjfJ5Fcfb58AcTGGb?si=wLax9T1PSFe3eKHPOAh-bQ',
  },
  {
    title: 'Kick a Dope Verse',
    subtitle: 'Uptown Tape',
    image: 'https://i.postimg.cc/PrMHLcFj/kickadopeverse.jpg',
    link: 'https://open.spotify.com/album/0YqYAE4LCjB610feWC0OpK?si=rJ_pUg-yRemquUrnmz7osQ',
  },
  {
    title: 'igory',
    subtitle: 'ocean view',
    image: 'https://i.postimg.cc/bvrqfTgj/igory.jpg',
    link: 'https://open.spotify.com/album/6kucfOGZ2dGI4G2rqqAW31?si=zA3E6jUYQ5emNhY5TCp-6g',
  },
  {
    title: 'J. Rawls',
    subtitle: '#jazzhop',
    image: 'https://i.postimg.cc/Bb93DG0q/jrawls.jpg',
    link: 'https://open.spotify.com/album/0CzzYYa80De9BaThHIE9mR?si=TnYphb0sQN2D_eFxLPmSOg',
  },
  {
    title: 'John Da Lemon',
    subtitle: 'Organic Ambience',
    image: 'https://i.postimg.cc/j2Hb4kxy/johndalemon.jpg',
    link: 'https://open.spotify.com/album/6Cns4acwXbmLeqrxAbULeq?si=K_fohlLST_GffWzQBeFoAw',
  },
  {
    title: 'Boora',
    subtitle: 'Soundogolism 2',
    image: 'https://i.postimg.cc/gc8mprVr/boora.jpg',
    link: 'https://open.spotify.com/album/78dbvKxJ5maCEzjfrkVV3b?si=5EwtBsCOSVKQFsuvbbqWTg',
  },
  {
    title: 'DOPE90',
    subtitle: 'Lo-Head 2',
    image: 'https://i.postimg.cc/yNGs1Zp3/dope90.jpg',
    link: 'https://open.spotify.com/album/2QmWYW1527fmjDl9LUHAG1?si=SeYBeu1iT52Y8yqib2st-g',
  },
  {
    title: 'FloFilz',
    subtitle: 'Speakthru',
    image: 'https://i.postimg.cc/6pYBPSd0/flofilz.jpg',
    link: 'https://open.spotify.com/album/4kYA3PqnQ9nKhMtREJqW0i?si=6RMgKTCXRKyfUpGK70Klmw',
  },
  {
    title: 'Nujabes',
    subtitle: 'Metaphorical Music',
    image: 'https://i.postimg.cc/t4XX2yVJ/nujabes.jpg',
    link: 'https://open.spotify.com/album/5FrjDW96mCYw9ECc74c637?si=q5CSP-HbSUurTIVVfNQ-wQ',
  },
  {
    title: 'Cultura',
    subtitle: 'Beats To Skate To, Vol.1',
    image: 'https://i.postimg.cc/tCnYfqcR/cultura.jpg',
    link: 'https://open.spotify.com/album/1n46VLE2E2BlcudV9198Lh?si=99e_VrvITYm13if9pYxAaw',
  },
  {
    title: 'Boora',
    subtitle: 'Nautiqua',
    image: 'https://i.postimg.cc/2jK12b2X/nautiqua.jpg',
    link: 'https://open.spotify.com/album/67ucvjfI9g1XJPkH9NDyOJ?si=ng1yK6HRS6WVAAbyp1Q-5A',
  },
  {
    title: 'Wun Two',
    subtitle: 'Penthouse',
    image: 'https://i.postimg.cc/HnRjxRrC/wun-two.jpg',
    link: 'https://open.spotify.com/album/0GttCWGCN1dQ5B9Yx9XPh2?si=b96xjLS7S8a3xyrvbmnMkw',
  },
  {
    title: 'Saib',
    subtitle: 'Unwind',
    image: 'https://i.postimg.cc/cHDvqrZC/saib.jpg',
    link: 'https://open.spotify.com/album/42R8dikH5xTKY4dUpqbAaW?si=QVNEwQKdT_-lwtKUJIAYig',
  },
  {
    title: 'lofi.samurai',
    subtitle: 'oldies',
    image: 'https://i.postimg.cc/x8cc9nTR/oldies.jpg',
    link: 'https://open.spotify.com/album/2TYJiRSU4FLphAkRCPWuT0?si=Sz-KbHIgRnyRt488neMANQ',
  },
  {
    title: 'Develop',
    subtitle: 'Origins of Light',
    image: 'https://i.postimg.cc/tgjZWK2q/origins.jpg',
    link: 'https://open.spotify.com/album/3XKXiyijaQHqJwYZIII3qS?si=MKd8l3nUQHeQOdUQvsJcYg',
  },
  {
    title: 'Franky A',
    subtitle: 'OG DIRTY TAPE 2',
    image: 'https://i.postimg.cc/qBb3SZMw/frankya.jpg',
    link: 'https://open.spotify.com/album/5CvLrUVM7Ci4xxpVhPMkVw?si=EojQZaMZS8G2rF8Kw2kx0g',
  },
  {
    title: 'Keytap',
    subtitle: 'Cassette Sound',
    image: 'https://i.postimg.cc/0ymK6kGX/keytap.jpg',
    link: 'https://open.spotify.com/album/4rvr89nsFSzdMyCrC1rMyg?si=bKF_rTvYQBimcJOChJ3WCA',
  },
  {
    title: 'Snares',
    subtitle: 'Expedition, Vol.9',
    image: 'https://i.postimg.cc/kGpRSDhz/snares.jpg',
    link: 'https://open.spotify.com/album/23VCRGkMolZniUhHTDGGJy?si=LuEuR1QKQj-qEknGq-rSIA',
  },
  {
    title: 'yeyts',
    subtitle: 'dilemma.',
    image: 'https://i.postimg.cc/MKnQSbnS/dilemma.jpg',
    link: 'https://open.spotify.com/album/0yCqxcBvaxow4h4kd9tOli?si=Cxyvl45fTOGyku94Gb3L7A',
  },
  {
    title: 'Lapti',
    subtitle: 'V Tiraj',
    image: 'https://i.postimg.cc/kG4tDWwW/vtiraj.jpg',
    link: 'https://open.spotify.com/album/7ke78hs2CJ2JMTwWP42LXt?si=lUBjxZvgQxOFJJS9nDRrXw',
  },
  {
    title: 'Ol` Burger Beats',
    subtitle: 'Dialogue.',
    image: 'https://i.postimg.cc/pTPjbwFG/dialogue.jpg',
    link: 'https://open.spotify.com/album/6F76UghtUqmcXSpmQszzVi?si=nDT9VCLzQA2xXkIT8baY2g',
  },
  {
    title: 'Cookin Soul',
    subtitle: 'Whateva, Vol.3',
    image: 'https://i.postimg.cc/zGRKnSNj/cookinsoul.jpg',
    link: 'https://open.spotify.com/album/2fqrB2RIltFZZkJ48SJXa9?si=kQ2aTgi5ShShLngB-u-MAQ',
  },
  {
    title: 'Develop',
    subtitle: 'Memories of the East',
    image: 'https://i.postimg.cc/mrycwm5Q/develop.jpg',
    link: 'https://open.spotify.com/album/6Jdt4u3tSPddvvCTdiCkJf?si=2Ftk4K29RIywTwthtHFNIA',
  },
  {
    title: 'lofi.samurai',
    subtitle: 'growth',
    image: 'https://i.postimg.cc/26j1Xnsg/growth.jpg',
    link: 'https://open.spotify.com/album/4QZ5nKde9BBVu61UjqFvR3?si=HWw88ScBTKiDuXZFGdGN8Q',
  },
];
